config/routes.rb
Rails.application.routes.draw do
  


  #どのURLにアクセスされたときに、controllerのどのメソッドを実行するかを設定する
  resources :likes
  resources :users
  resources :posts #一般的な処理を一気に設定する
  get "users/:id/likes" => "users#likes" #いいねされた投稿を一覧で表示する。likesアクションをusers ctlr内に作成
       #どのユーザーかを判断するためにidを含ませる
  post "likes/:post_id/destroy" => "likes#destroy"
  post "likes/:post_id/create" => "likes#create"
  post "logout" => "users#logout" #sessionの値を変更するときはpost
  post "login" => "users#login" #fromの値を送信するのでpost。postのルーティングを探す
  get "login" => "users#login_form"
  post "users/:id/update" => "users#update"
  post "posts/:id/update" => "posts#update"
  
  root "home#top"
  get "about" => "home#about"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
	validates :user_id, {presence:true}
	validates :post_id, {presence:true}
end

app/models/post.rb
class Post < ApplicationRecord
	validates :content, {presence:true, length: {maximum: 100}}
	validates :user_id, {presence:true}


	def user
		return User.find_by(id:self.user_id)
	end#posts_controllerのshowアクションで@userに@post.user(このreturnメソッドを代入)	

end
#postsテーブルを使うためにモデルというクラスを用いてデータベースを使う。
#rails g modelコマンドでpostsテーブルを操作するためのPostモデルができる。
#AppicationRecordを継承したクラス(Post)をモデルと呼ぶ
#rails g model Post content:text のPostはモデル名、contentはカラム名、textはデータ型

#validates :検証カラム名, {presence:true}
#Railsではモデル内にインスタンスメソッドを定義することができ、postインスタンスに対して用いることができる

app/models/user.rb
class User < ApplicationRecord #rails g model Userの時にできるファイル
	validates :name,  {presence: true}

	validates :email, {presence: true, uniqueness: true}#同じemailアドレスを保存させない

    validates :password, {presence: true}

    def posts #ユーザーが作成した投稿をまとめて取得できる
    	return Post.where(user_id: self.id) #self.idの投稿を戻り値とする
    	
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #全てのコントローラで共通する処理はapplicationコントローラにまとめることができる。
  #set_current_userメソッドを定義する
  before_action :set_current_user #set_current_userメソッドが各コントローラーで実行される


  def set_current_user
  	@current_user = User.find_by(id: session[:user_id])#現在ログイン中のユーザーを取得
  	
  end

  def authenticate_user #ログイン中のユーザーが存在するかチェックできる(ログインしていないとURLで直接アクセスすることはできない)
  	if @current_user == nil
  		flash[:notice] = "required to log in"
  		redirect_to("/login")
  	end
  end

  def forbid_login_user
  	if @current_user #ログイン済みのユーザーだった場合
  		flash[:notice] = "You are already logged in"
  		redirect_to posts_path
  	end
  	
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :forbid_login_user, {only:[:top]}

  def top

  end
  
  def about
  	
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user #このcontrollerはログインしているユーザーのみに制限
  
  
  def create #いいねするデータとされるデータを取得し、保存
  	@like = Like.new(
  		user_id: @current_user.id,
  		post_id: params[:post_id]
  	)
  	@like.save
  	redirect_to("/posts/#{params[:post_id]}") #投稿者の詳細ページ
  end
  
  
  def destroy
    @like = Like.find_by(
      user_id:@current_user.id, 
      post_id:params[:post_id]
      )#これらを基に削除すべきLikeデータを取得
    @like.destroy
    redirect_to("/posts/#{params[:post_id]}")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user
  before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}

  def index
  	@posts = Post.all.order(created_at: :desc)#Postモデルのインスタンスを全て取得
  end

  def show
  	@post = Post.find_by(id: params[:id]) #idカラムがparams[:id]である投稿データを取得している	
  	@user = @post.user #投稿者を特定すると、returnでそのインスタンス自身を返す
  	@likes_count = Like.where(post_id: @post.id).count#countメソッドを使っていいねの数を数える
  end	

  def new
  	@post = Post.new #(このPostはモデル名。Postモデルに新規作成するということ)

  end

  def create #update(更新)と違って新しく作る
  	@post = Post.new(
  		content: params[:content],
  		user_id: @current_user.id#新規投稿時にuser_idの値を入れる
  		)
  	if @post.save
  	flash[:notice] = "created a new post"
  	redirect_to posts_path
    else
    	render("posts/new")
    end
  end

  def edit
  	@post = Post.find_by(id: params[:id])
  	
  end

  def update
  	@post = Post.find_by(id: params[:id])
  	@post.content = params[:content] #フォームの値を受け取る
  	if @post.save
  	   redirect_to posts_path
  	   flash[:notice] = "editted"
  	else
  	   render("posts/edit") #redirectと違い、このアクション内で定義した@変数をビューでそのまま使える
  	end #render("フォルダ名/ファイル名") メソッドは引数に、呼び出したいビューのフォルダ名とファイル名を指定します。
        # ファイル名の部分には拡張子（.html.erb）が必要ない
  	
  end

  def destroy
  	@post = Post.find_by(id: params[:id])
  	@post.destroy
  	flash[:notice] = "deleted"
  	redirect_to posts_path
  		
  end	

  def ensure_correct_user #投稿者とログイン中のユーザーが異なるかを調べるメソッド
  	@post = Post.find_by(id: params[:id])
  	if @post.user_id != @current_user.id
  		flash[:notice] = "you are not entitled"
  		redirect_to posts_path
  	end
  	
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user, {only:[:index, :show, :edit, :update]}
  before_action :forbid_login_user, {only:[:new, :create, :login_form, :login]}
  before_action :ensure_correct_user, {only:[:edit, :update]}#異なるユーザーが編集できないように正しいユーザーかを確かめる

  def index
  	@users = User.all
  end

  def show
  	@user = User.find_by(id: params[:id])
  	
  end
  def new #signup(新規ユーザー登録)
  	@user = User.new #ユーザー登録ページにアクセスした時のUserインスタンス
  	#新規登録ページのビューでUserクラスのインスタンスを使うようになったため、
#新規登録ページのアクションでも@user = User.newのようにしてインスタンスを用意します。
  end
  def create
  	@user = User.new(
  	name: params[:name], 
  	email: params[:email],
  	image_name: "IMG_0080.jpg",
  	password: params[:password]
  	)#:nameと:emailはname属性の値
  	if @user.save
  		session[:user_id] = @user.id #新規登録に成功したらログインする
  		redirect_to users_path
  		flash[:notice] = "user created"
  	else
  	render("users/new")
  	end	
  end

  def edit
  	@user = User.find_by(id: params[:id])
  	
  end

  def update #編集した時にデータベースに保存する
  	@user = User.find_by(id: params[:id])#投稿データを取得する
  	@user.name = params[:name] #フォームから送信された値
  	@user.email = params[:email] 
  	if params[:image] #画像が送信されている場合
  	@user.image_name = "#{@user.id}.jpg" #画像のファイル名をimage_nameカラムに保存
  	image = params[:image] #publicフォルダ内に画像を作成
  	File.binwrite("public/user_images/#{@user.image_name}",image.read)#画像データ取得
  	#ファイルの作成にFileクラスを使う。(画像データはFile.writeではなくFile.binwriteを用いる)
  	end
  	if @user.save
  	   flash[:notice] = "user updated"
  	   redirect_to users_path
    else
    	render("users/edit")
    end
   end

   def login_form
    	
   end

   def login
   	@user = User.find_by(email: params[:email], password: params[:password])
     #formに入力されたemail,passwordから該当するユーザーを取得し、ログインするユーザーを特定
   	if @user #userがいる場合
   		session[:user_id] = @user.id #ページを移動してもユーザー情報を保持し続ける(sessionの値はブラウザに保存される)
   		flash[:notice] = "you are logged in"
   		redirect_to posts_path
   	else 
   		@error_message = "email address or password you entered are wrong"
   		@email = params[:email]
   		@password = params[:password]

   		render("users/login_form")
   	end
   end

   def logout
   	session[:user_id] = nil #nilを代入してログアウトする
   	flash[:notice] = "you are logged out"
   	redirect_to login_path
   end

   def ensure_correct_user
   	if @current_user.id != params[:id].to_i#編集したいユーザーid(数値を取得するにはto_iメソッドを使う)
   		flash[:notice] = "User is wrong. Not entitled to edit"
   	end
   	
   end

   def likes
   	@user = User.find_by(id: params[:id])
   	@likes = Like.where(user_id:@user.id)#ユーザーに関するデータをlikesテーブルから取得
   	#@userと紐付くLikeインスタンスの配列をデータベースから取得
   	
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div class="top-main">
	<h2>About this App</h2>
	<p>
		SNS SERVICE
		You can communicate each other by tweeting
	</p>
	<img class="about-imag" src="">

</div>

app/views/home/top.html.erb
<div class="main top-main">
	<div class="top-message">
		<h2>Connect with each other regardless of boundaries</h2>
		<p>Tweet something you want to tell</p>
		<%= link_to "About us", about_path %>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
  	<header>
	<div class="header-logo">
	  <% if @current_user %>
          <%= link_to "Let's Tweet", posts_path %>
      <% else %>
          <%= link_to "Let's Tweet", root_path %>
      <% end %>
	</div>
	<ul class="header-menus">
		<% if @current_user %> <!-- session[:user_id]-->
		    <ol>
		    	<%= link_to(@current_user.name, "/users/#{@current_user.id}") %>
		    </ol>
			<ol>
			    <%= link_to "Index", posts_path %>
			</ol>
			<ol>
			    <%= link_to "POST", new_post_path %>	
			</ol>
			<ol>
				<%= link_to "Logout", logout_path, {method: :post} %>
			</ol>
		<% else %>
			<ol>
			    <%= link_to "About this app", about_path %>	    
			</ol>

			<ol>
			    <%= link_to "Users", users_path %>	
		    </ol>
		    <ol>
		    	<%= link_to "Create User", new_user_path %>
		    </ol>
		    <ol>
		    	<%= link_to "Login" , login_path %>
		    </ol>
	    <% end %>
	    <!--・ログイン状態で表示する項目(・session[:user_id],・投稿一覧、・新規投稿、ログアウト)
　　　　      ・ログアウト状態で表示する項目(・about app,・ログイン)-->

	</ul>

</header>
<% if flash[:notice]#delete,edit,postした時に適用するのでapplication.htmlにこれを書く%>
   <div class="flash-notice">
      <%= flash[:notice] %>
   </div>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<p>edit something</p>
<%= form_tag("/posts/#{@post.id}/update") do %>
      <div class="form">
        <div class="form-body">
          <% @post.errors.full_messages.each do |message| %>
	          <div class="form-error"> 
	          	<%= message %> 
	          	<%#saveメソッドを呼び出した際にvalidationに失敗すると自動的にメッセージが生成される%>
	          </div>
          <% end %>
          <textarea name="content"><%= @post.content %></textarea>
          <input type="submit" value="post">
        </div>
      </div>
<% end %> 

app/views/posts/index.html.erb
<div class="main posts-index">
  <div class="container">
    <% @posts.each do |post| %>
      <div class="posts-index-item">
          <%= link_to(post.content, "/posts/#{post.id}") %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main posts-item">
    <div class="container">
		<h1 class="form-heading">POST SOMETHING!!</h1>
		<% #createアクションで受け取った投稿データをデータベースに保存する%>	
		<% #createアクションに飛ばす%>
		<%= form_tag("/posts") do %>
      <div class="form">
        <div class="form-body">
        	<% @post.errors.full_messages.each do |message| %>
	          <div class="form-error"> 
	          	<%= message %> 
	          	<%#saveメソッドを呼び出した際にvalidationに失敗すると自動的にメッセージが生成される%>
	          </div>
            <% end %>
          <textarea name="content"></textarea>
          <input type="submit" value="post">
        </div>
      </div>
    <% end %>
    </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  
	<img src="<%= "/user_images/#{@user.image_name}"%>">
	<%= link_to(@user.name, "/users/#{@user.id}") %> 
	<p>
		<%= @post.content %>
	</p>

	<p>
		<%= @post.created_at %>
	</p>
	<% if Like.find_by(user_id:@current_user.id, post_id:@post.id) %><!--2つのデータがあるとき-->
		  <%= link_to( "/likes/#{@post.id}/destroy", {method: "post"})do %>
		    <span class="fa fa-heart like-btn-unlike"></span>
		  <% end %>
	<% else %>
		 <%= link_to("/likes/#{@post.id}/create",{method: "post"})do %>
		    <span class="fa fa-heart like-btn"></span>
		 <% end %>
	<% end %>

    <%= @likes_count %>

	<% if @post.user_id == @current_user.id %><!--投稿者だけが編集できるようにする-->
		<div class="post-menus">
			<ul>
				<li>
					<%= link_to "EDIT", edit_post_path %>
				</li>
				<li>
					<%= link_to("DELETE","/posts/#{@post.id}", method: :delete, data: {confirm: "Are you sure?"})%>
				</li>

			</ul>
		</div>
	<% end %>
</div>

app/views/users/edit.html.erb
<div class="top-main">

  <% @user.errors.full_messages.each do |message| %>
              <div class="form-error"> 
                <%= message %> 
                <%#updateアクションのsaveメソッドを呼び出した際にvalidationに失敗すると自動的にメッセージが生成される%>
              </div>
  <% end %>


  <%= form_tag("/users/#{@user.id}/update",{multipart: true}) do %>
        
            <p>User Name</p>
            <input name="name" value="<%= @user.name %>">
            <p>email address</p>
            <input name="email" value="<%= @user.email %>">
            <p>picture</p>
            <input type="file" name="image">
            <input type="submit" value="submit">
          
  <% end %>
  <!-- 画像の送信は特殊なので、form_tagに{multipart: true}を追加する -->
</div>

app/views/users/index.html.erb
<div class="main-users-index">
	<div class="container">
        <h1>User Index</h1>
	    <% @users.each do |user| %>
	     <div class="posts-index-item">
	     <img src="<%= "/user_images/#{user.image_name}" %>">
	     <%= link_to user.name, user_path(user)%>

	     </div>
	    <% end %>
	</div>
</div> 

app/views/users/likes.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <img src="<%= "/user_images/#{@user.image_name}" %>">
      <h2><%= @user.name %></h2>
      <p><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
        <%= link_to("編集", "/users/#{@user.id}/edit") %>
      <% end %>
    </div>
    
    <ul class="user-tabs">
      <li><%= link_to("投稿", "/users/#{@user.id}") %></li>
      <li class="active"><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
    </ul>
    
    
    <% @likes.each do |like|%>
      <% post = Post.find_by(id: like.post_id) %><!--変数likeに紐づくPostインスタンスをdbから取得-->
      <div class="posts-index-item">
        <div class="post-left">
          <img src="<%= "/user_images/#{post.user.image_name}" %>">
        </div>
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to(post.user.name, "/users/#{post.user.id}") %>
          </div>
          <%= link_to(post.content, "/posts/#{post.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="container">
    <div class="form-heading">Login Form</div>
    <div class="form users-form">
    	<% if @error_message %>
          <div class="form-error">
            <%= @error_message %>
          </div>
        <% end %>
    <%= form_tag("/login") do %>	
      <div class="form-body">
         <p>email address</p>
		<input name="email" value="<%= @email%>">
		<p>password</p>
		<input type="password" name="password" value="<%= @password%>">
		<input type="submit" value="login">
       
      </div>
     <% end %>
    </div>
  </div>
  <!--formの送信先がlocalhost:3000/loginということ

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">New user register</div>
    <div class="form users-form">
    	
      <div class="form-body">
    <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
    <% end %>
    <%= form_tag("/users") do %>
        <p>user name</p>
        <input name="name"><!-- #name属性の値が送信されるハッシュのキーになる-->
        
        <p>email address</p>
        <input name="email">

        <p>password</p>
        <input type="password" name="password" value="<%= @user.password%>">


    
        <input type="submit" value="create">
      </div>
    <% end %> 
    </div>
  </div>
</div>

app/views/users/show.html.erb
	
<div class="user-show">
	
	<p><img src="<%= "/user_images/#{@user.image_name}"%>">
		<!--#画像はpublic/user_imagesフォルダに保存されているので、src属性の値は「/user_images/ファイル名」とする必要がある --></p>
	<h2>username: <%= @user.name %></h2>
	<p>user.id: <%= @user.id %></p>
	<p>user.email: <%= @user.email %></p>

	<% if @user.id == @current_user.id %> <!--詳細ページのユーザーのidとログイン中のユーザーのidが等しい場合 -->
	 <%= link_to("edit","/users/#{@user.id}/edit")%>
	<% end %>

	<ul class="user-tabs">
	      <li><%= link_to("see what you liked", "/users/#{@user.id}/likes") %></li>
	</ul>
    
	
</div>